### ISSUE TITLE
backporting to 1.21

### ISSUE THREAD

**Issue by AXCWG** [borisshoes/ArcanaNovum#1]
is that doable? It's ok if its not.

**Comment by borisshoes** [comment]
I have uploaded 1.21 compatible jars to the Modrinth page and appended them to the latest GitHub release.

However, I would seriously consider updating your server to 1.21.1, as 1.21 contains serious vulnerabilities, and an update causes no additional hassle to your players as both versions are network compatible.

**Comment by unilock** [comment]
Additionally, the vast majority of 1.21 mods will work without changes on 1.21.1.

**Comment by borisshoes** [comment]
> Additionally, the vast majority of 1.21 mods will work without changes on 1.21.1.

Yeah, although when I compiled v3.0.0, I had the fabric mod config set to use MC 1.21.1 or greater, since I was trying to track down a bug and had to use the latest 1.21.1 polymer version to rule out a possible cause. Most other mods that are labelled as 1.21.x will be forward compatible with 1.21.1 without issue.

**Comment by AXCWG** [comment]
thanks for replying!
